import type { Metadata } from "next";
import { DM_Sans, Playfair_Display } from "next/font/google"; // Import your specific fonts
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			// Add the new font variables here
			className={`h-full antialiased`}
		>
			<body className="min-h-full h-full flex flex-col">{children}</body>
		</html>
	);
}
